spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-data-common
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        query:
          fail_on_pagination_over_collection_fetch: true
    open-in-view: false
server:
  port: 8087
log4j:
  logger:
    org:
      hibernate:
        type: trace